[features]
seeds = false
[programs.devnet]
bo_marketplace = "22YCvsiJSir1Hb7ihcTvGGXg9uA84AfYjN6vsqphkuEx"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/braeden/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
